### ISSUE TITLE
v0.6: Fatal error: Cannot access self:: when no class scope is active

### ISSUE THREAD

**Issue by timkirtley** [Upstatement/jigsaw#13]
Hey,

Just updated saw and update to v0.6 was available within WordPress..  didn't see a changelog but assumed the best :)

Now any post types that I've added a column to dont load properly - wp debug shows this error:

Fatal error: Cannot access self:: when no class scope is active in /wp-content/plugins/jigsaw/jigsaw.php on line 188

**Comment by jarednova** [comment]
@timkirtley thanks for the headsup! that didn't come up in my tests. What version of PHP and WP are you running?

**Comment by timkirtley** [comment]
Hey, no worries!    This is on PHP 5.3.3 and WP 4.4.1




On 26 Jan 2016, at 11:56, Jared Novack <notifications@github.com> wrote:

@timkirtley <https://github.com/timkirtley> thanks for the headsup! that didn't come up in my tests. What version of PHP and WP are you running?

**Comment by jarednova** [comment]
@timkirtley give the new version a try! (also added a changelog so you know what's going on!)

**Comment by timkirtley** [comment]
Okay, now have the following with the new 0.6.1:

Fatal error: Call to protected method Jigsaw::column_title_filter() from context '' in /wp-content/plugins/jigsaw/jigsaw.php on line 188

**Comment by jarednova** [comment]
grumble grumble grumble

**Comment by timkirtley** [comment]
Ha, sorry :)

**Comment by timkirtley** [comment]
0.6.2 seems perfect now, thanks!

**Comment by jarednova** [comment]
awesome, thanks again for the bug report @timkirtley! I'm glad we caught that soon after the release
