### ISSUE TITLE
Question! Does jigsaw support column sorting?

### ISSUE THREAD

**Issue by Daronspence** [Upstatement/jigsaw#6]
Title says it all. Would be neat if this was built in. The docs don't seem to cover it and I don't have any projects to throw in on right this second.

**Comment by jarednova** [comment]
@Daronspence and @LemonyDesign can you provide an example of the kinds of columns you would want to sort? Unfortunately, WP makes the process a bit messy. Here's what I'm working with so far...

```php
//add a column
Jigsaw::add_column('my_post_type', 'Post ID', function($id) {
	echo $id;
});
// enable sorting, the third argument is the key on the object to sort by. Would this suffice?
Jigsaw::sort_column('my_post_type', 'Post ID', 'ID');
```

**Comment by Daronspence** [comment]
Wordpress does sorting by date as the default. Then clicking title will sort by the title string ASC or DESC. I would imagine sorting in jigsaw would be similar. Enable it for sorting by ASC or DESC with data that supports it. So I can't sort by thumbnail image obviously.

**Comment by HellFireAE** [comment]
Working on a project right now that needs sorting. What's the status on this feature?

**Comment by iltdev** [comment]
Is this feature still being developed? It would be fantastic is sorting was available.

**Comment by jcutrell** [comment]
Gonna put a little word in here - I'd love this feature as well. Gonna start including Jigsaw on all projects, especially if this is in there.

**Comment by padjodev** [comment]
Looks like a great project. I'm going to add it into my custom base theme for all clients however the sorting feature would be the icing on the cake... Any word?

**Comment by jarednova** [comment]
Hey @jcutrell @padjodev — I've looked into sorting a few times and it's waaay more complicated to add that I expected. I'll take a look with fresh eyes this weekend, but in the past I've found it to be far messier than I would have expected. PRs welcome!

**Comment by padjodev** [comment]
Great class either way... Ive added it to my default theme framework by default to show post views in a column and its working perfectly, so thanks for that at least :)

**Comment by quantumleap33** [comment]
Hello, if it's any help, I managed to do sorting this way:

```
// Make certain admin columns sortable
function sortable_columns() {
  return array(
    'th-id'      => 'meta-name'
  );
}
```

th-id = the th tag id that I got from Firebug
meta-name = the meta key name

Hope it helps and thanks for the neat plugin!

**Comment by jarednova** [comment]
Thanks group for the nudges. I realized why I never implemented this in the first place, and it's because I made it more challenging than it needed to be.

So here's the catch: WordPress can only sort on things accesible to WP_Query (like a meta key). BUT if you're sorting on a meta key, awesome! just add this code..

```php
Jigsaw::sort_column($post_types, $label, $meta_key, $numeric);
```

For example...
```php
Jigsaw::sort_column('book', 'ISBN', 'isbn', true);
Jigsaw::sort_column('post', 'Location', 'location_name');
```

... give it a try! lemme know what you think and I'll make a new release:

https://github.com/Upstatement/jigsaw/pull/14

**Comment by quantumleap33** [comment]
There is a problem where any blank values in one of those columns make related posts hidden on sorting.

**Comment by chrilleferna** [comment]
I patched in the sort_column function from @jardenova and it seems to work perfectly. Would be nice if the author pulled it in to a new release.

**Comment by jarednova** [comment]
@chrilleferna merged!

**Comment by danbraun** [comment]
Hello! I've started using the sort_column method. However, there seems to be a bug where even though I pass a $meta_key in the 3rd argument, the sort_column method would still rather use the dynamically created $key value for the meta key (on line 209: $key = sanitize_title( $label );)

**Comment by shadowshades** [comment]
If someone is still interrested, I found the solution. Change the lines 214 and 215 :
`add_filter( 'manage_edit-'.$post_type.'_sortable_columns', function($cols) use ( $key ) {
    $cols[$key] = $key;`

to :

`add_filter( 'manage_edit-'.$post_type.'_sortable_columns', function($cols) use ( $key, $meta_key ) {
    $cols[$key] = $meta_key;`

**Comment by jarednova** [comment]
@shadowshades can you submit a PR? would love to pull that in and give you appropriate credit

**Comment by shadowshades** [comment]
@jarednova sorry for the late reply! Sorry I can't submit a PR. Can you make this change for a next update ? Thank!

**Comment by jarednova** [comment]
yeah, I can make that happen. thanks!
